services:
  backend:
    build: ./backend
    container_name: gunter-backend
    restart: unless-stopped
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    networks:
      - gunternet
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  frontend:
    build: ./frontend
    container_name: gunter-frontend
    restart: unless-stopped
    ports:
      - 3333:80
    networks:
      - gunternet
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

networks:
  gunternet:
    driver: bridge